copy /b ^
..\..\libs\vec2.min.js + ^
..\..\libs\jquery.mousewheel.js + ^
..\..\libs\jquery-2.1.3.js + ^
..\..\libs\GreenSock\easing\EasePack.js + ^
..\..\libs\GreenSock\TweenMax.min.js + ^
..\..\libs\pixi.dev.js + ^
..\..\libs\soundjs-0.5.2.min.js + ^
ZSound.js + ^
LevelManager.js + ^
Utils.js + ^
Stages\StageManager.js + ^
Stages\CustomStage.js + ^
Stages\MainMenu.js + ^
Stages\LevSel.js + ^
Stages\GameStage.js + ^
Stages\Credits.js + ^
Stages\WinGame.js + ^
Stages\AchStage.js + ^
Stages\CharStage.js + ^
Stages\ShopStage.js + ^
Stages\ScoreStage.js + ^
ZPool.js + ^
Objects\CObj.js + ^
Objects\CBomb.js + ^
Objects\CButton.js + ^
Objects\ZCJoint.js + ^
Objects\CTextField.js + ^
Objects\Notification.js + ^
Objects\CNotArrow.js + ^
Objects\CHPBar.js + ^
LiveObjects\CLiveObj.js + ^
LiveObjects\CPlayer.js + ^
Objects\CBullet.js + ^
Objects\FloorObj.js + ^
Objects\LauncherBG.js + ^
Objects\CGrenade.js + ^
Objects\CPlane.js + ^
Monsters\CMonster.js + ^
Monsters\JumpMon.js + ^
Monsters\CDrone.js + ^
Monsters\CObstacle.js + ^
Monsters\CBarrel.js + ^
Monsters\Boss1.js + ^
Monsters\Boss2.js + ^
Monsters\MM.js + ^
Monsters\BonusMonGnome.js + ^
Objects\CCoin.js + ^
Objects\CScrollbar.js + ^
Objects\CircleBar.js + ^
CEActionGUI.js + ^
Weapons\CWeapon.js + ^
Weapons\CPistol.js + ^
Weapons\CQueueGun.js + ^
Weapons\CLaser.js + ^
Weapons\CGrenadeLauncher.js + ^
Weapons\WeapBalance.js + ^
Boosters\CBooster.js + ^
Boosters\CDoubleBooster.js + ^
Boosters\CHeartBooster.js + ^
Boosters\CMagnetBooster.js + ^
Boosters\CSupermanBooster.js + ^
Boosters\CTabletsBooster.js + ^
PlayerData.js + ^
dbinit.js + ^
init.js + ^
resizeend.coffee.js + ^
gamefile.js ^
all.js
java -jar compiler.jar --js all.js --js_output_file all.min.js